export const TOKENS = {
  logger: Symbol.for('logger'),
  envAnalyzer: Symbol.for('envAnlz'),
  env: Symbol.for('env'),
  fs: Symbol.for('fs'),
  cfgReader: Symbol.for('cfgReader'),
  depsReader: Symbol.for('depsReader'),
  styleAnlz: Symbol.for('styleAnlz'),
  testAnlz: Symbol.for('testAnlz'),
  styBldrFctry: Symbol.for('styleBuilderFact'),
  cmpGen: Symbol.for('cmpGen'),
  componentTestsBuilder: Symbol.for('componentTestsBuilder'),
  componentBuilderFacade: Symbol.for('componentBuilderFacade'),
  cmpGenInputNrmlz: Symbol.for('cmpGenInputNrmlz'),
  fileWriter: Symbol.for('fileWriter'),
  ui: Symbol.for('ui'),
  pkgJsonReader: Symbol.for('pkgJsonReader'),
  codeFormatterCfgReader: Symbol.for('codeFormatterCfgReader'),
  codeFormatter: Symbol.for('codeFormatter'),
  componentStoriesBuilder: Symbol.for('componentStoriesBuilder'),
  cfgSetuper: Symbol.for('cfgSetuper'),
};
